on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ "master" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: nodejs project information
        id: projectinfo
        uses: gregoranders/nodejs-project-info@v0.0.18
      - name: create release action
        id: createrelease
        uses: gregoranders/nodejs-create-release@v0.0.18
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          PACKAGE_JSON: ${{ steps.projectinfo.outputs.context }}
        with:
          tag_name: v${{ steps.projectinfo.outputs.version }}
          release_name: ${{ steps.projectinfo.outputs.name }} - ${{ steps.projectinfo.outputs.version }} Release
          body: |
            Changes in this Release
            - All changes described from the release in this readme
          draft: false
          target: ${{ github.ref }}
          prerelease: false
